Patch 8
lablab-ai/community-content pull request #319
Opened 2023-09-14 02:29 UTC by feliciien

/claim #296

2023-09-14 07:34 UTC, ezzcodeezzlife commented
there are two tutorials, and both do not meet the issue requirements, please make sure to cover them all 🚀 thanks you!

2023-09-14 09:55 UTC, feliciien commented
@ezzcodeezzlife, this has been marked as “not planned.” Am I allowed to close my pull request, or is it necessary for me to continue working on it?

2023-09-18 07:14 UTC, jmisilo commented on auto-gpt-tutorial-how-to-create-a-website-with-auto-gpt.mdx
> +title: "Use AutoGPT to create  website  faster"
please remove double spaces

2023-09-18 09:13 UTC, ezzcodeezzlife commented on auto-gpt-tutorial-how-to-create-a-website-with-auto-gpt.mdx
> +title: "Use AutoGPT to create  website  faster"
> please remove double spaces

@feliciien

2023-09-26 10:55 UTC, ezzcodeezzlife commented
> there are two tutorials, and both do not meet the issue requirements, please make sure to cover them all 🚀 thanks you!

still an issue!

2023-09-26 15:49 UTC, feliciien commented
Ok

2023-10-06 12:52 UTC, ezzcodeezzlife commented
@feliciien the content is too similar to your previous tutorials

2023-10-06 12:53 UTC, ezzcodeezzlife requested changes
⬆️

2023-10-06 14:19 UTC, feliciien commented
Can you give me suggestions of content.?

2023-10-09 08:50 UTC, ezzcodeezzlife commented
https://github.com/lablab-ai/community-content/issues/296 unfortunately closed

2023-10-09 08:50 UTC, closed without merging